# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171217_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ubigeo',
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(default='', max_length=50, verbose_name='ubicacion'),
            preserve_default=False,
        ),
    ]
