# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 04:27
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20171216_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('package'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)]),
        ),
    ]
