# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20171216_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)])),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.RemoveField(
            model_name='packageimage',
            name='package',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=stdimage.models.StdImageField(default='', upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
        migrations.AddField(
            model_name='activity',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
    ]
