# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 17:20
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20171217_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name')),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name')),
        ),
    ]
